In [9]:
import pandas as pd

In [10]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
caminho = "https://www-usr.inf.ufsm.br/~joaquim/UFSM/DM/ds/AgeOfMythology_work.csv"
df = pd.read_csv(caminho, dtype="string", keep_default_na=False, encoding="utf-8")

In [11]:
df

,Unit,Age,Cost,Pop,DmgHack,DmgPierce,DmgCrush,Range,HP,ArmorHack,ArmorPierce,ArmorCrush,Speed,LOS,Train time,Bonus,Other,Class
0,Pegasus,1,50F 2Fv,2,--,--,--,0,140,50,50,99,5,18,6,,,Myth Unit
1,Centaur,2,200W 15Fv,3,--,12,--,12,220,25,35,80,5,20,19,"Myth units, -Heroes",,Myth Unit
2,Cyclops,2,250F 22Fv,4,15,--,12,2,600,40,50,80,3.2,16,20,Myth units,,Myth Unit
3,Minotaur,2,200F 16Fv,4,15,--,10,2,300,60,50,80,4,20,20,Myth units,,Myth Unit
4,Hydra,3,250F 28Fv,5,20,--,10,3,800,60,40,80,4,16,20,"Myth units, -Heroes",,Myth Unit
5,Manticore,3,300W 28Fv,5,--,11**,--,16,420,30,60,80,4.3,20,17,"Myth units, -Heroes",,Myth Unit
6,Nemean Lion,3,200G 25Fv,4,20,--,10,1,660,30,60,80,4.8,16,20,"Myth units, -Heroes",,Myth Unit
7,Colossus,4,300G 40Fv,5,20,--,50,3,1100_,50,80,80,2.4,16,24,"Myth units, -Heroes",,Myth Unit
8,Chimera,4,300G 30Fv,4,20,--,--,1,800,60,60,80,5.3,16,20,"Myth units, -Heroes",,Myth Unit
9,Medusa,4,250G 40Fv,5,--,15,12.5,10,360,60,70,80,4.3,18,20,"Myth units, -Heroes",,Myth Unit
10,Anubite,2,100F 15Fv,3,13,--,--,1,200,60,55,80,5.3,16,9,Myth units,,Myth Unit
11,Sphinx,2,60F 10Fv,4,11.25,--,5,1,300,45,60,80,5.3,22,17,Myth units,,Myth Unit
12,Wadjet,2,150W 15Fv,3,--,16,--,18,240,20,30,80,3.8,20,17,-Heroes,,Myth Unit
13,Petsuchos,3,200G 20Fv,4,--,50,20,20,480,30,40,80,2.6,24,20,-Heroes,,Myth Unit
14,Roc,3,150G 15Fv,3,--,--,--,none,350,30,25,80,4.8,20,14,,Transports,Myth Unit
15,Scarab,3,300F 20Fv,5,6,--,12,1,670,30,75,80,3.2,16,20,Buildings,,Myth Unit
16,Scorpion Man,3,150W 25Fv,4,25,--,--,1,500,50,40,80,5,16,20,"Myth units, -Heroes",,Myth Unit
17,Avenger,4,250F 30Fv,4,28,--,--,1,600,60%,40%,80%,5.3,18,24,"Myth units, -Heroes",,Myth Unit
18,Mummy,4,200G 35Fv,5,--,12,--,12,350,35,50,80,4,18,17,,,Myth Unit
19,Phoenix,4,200G 30Fv,5,30,--,30,4,400,15,55,80,3.6,20,20,-Heroes,,Myth Unit
20,Einherjar,2,175G 15Fv,3,15,--,10,1,275,70,60,80,3.2,16,17,Myth units,,Myth Unit
21,Troll,2,150W 15Fv,4,--,13,--,14,200,50,50,80,3.6,20,15,"Myth units, -Heroes",,Myth Unit
22,Valkyrie,2,200F 20Fv,4,12,--,--,1,375,55,70,80,6,20,17,Myth units,,Myth Unit
23,Battle Boar,3,250G 30Fv,4,20,--,20,1,720,60,60,80,5.3,16,20,"Myth units, -Heroes",,Myth Unit
24,Frost Giant,3,200G 25Fv,5,18,--,12,2,600,55,70,80,3.8,20,24,x3 Myth units,,Myth Unit
25,Mountain Giant,3,300F 30Fv,5,20,--,25,2,1200,45,30,80,3.2,16,17,"x2 Myth units, x0.8 Heroes",,Myth Unit
26,Fenris Wolf,4,150G 15Fv,3,15,--,--,1,420,40,50,80,4,16,14,"x2 Myth units, x0.5 Heroes",,Myth Unit
27,Fire Giant,4,300G 35Fv,5,15,--,10,14,600,60,80,80,3.2,18,24,x0.25 Heroes,,Myth Unit
28,Jason,1,100F 50G,2,9,--,--,1,240,25,35,99,4.3,16,9,Myth units,,Hero
29,Odysseus,2,200W 2Fv,2,--,8*,--,18,320,20,30,99,4,20,17,Myth units,,Hero
30,Heracles,3,350F 4Fv,3,10,--,--,1,400,25,40,99,4.3,16,23,Myth units,,Hero
31,Bellerophon,4,400G 6Fv,4,20,--,--,2,400,20,40,99,6,16,27,Myth units,,Hero
32,Theseus,1,100F 50G,2,9,--,--,1,240,25,40,99,4.3,16,9,Myth units,,Hero
33,Hippolyta,2,200W 2Fv,2,--,9,--,18,240,20,30,99,4.3,20,17,Myth units,,Hero
34,Atalanta,3,350F 4Fv,3,8,--,--,2,350,35,40,99,6,16,23,Myth units,,Hero
35,Polyphemus,4,400G 6Fv,4,15,--,5,2,540,40,40,99,3.2,20,27,Myth units,,Hero
36,The Argo,4,250F 8Fv,3,--,8,--,16,480,40,25,20,4.8,24,17,Myth units,Transports,Hero
37,Ajax,1,100F 50G,2,9,--,--,1,240,30,25,99,4.3,16,9,Myth units,,Hero
38,Chiron,2,200W 2Fv,2,--,7,--,14,300,20,20,99,5.3,20,17,Myth units,,Hero
39,Achilles,3,350F 4Fv,3,9,--,--,1,340,40,45,99,5.5,16,23,Myth units,,Hero
40,Perseus,4,400G 6Fv,4,7,--,--,1,360,20,40,99,4.3,16,27,Myth units,,Hero
41,Priest,1,100G,2,--,3,--,3,90,10,0,99,3.6,8,9,Myth units,,Hero
42,Pharaoh,1,--,0,--,12,--,4,100,15,15,99,4,16,--,Myth units,,Hero
43,Son of Osiris,--,--,--,60,--,--,18,546,30,50,99,3.6,25,--,Myth units,Up to 4,Hero
44,Hersir,2,80F 40G,3,8,--,--,1,130,20,15,99,4.2,16,23,Myth units,Double Favor,Hero
45,Hero of Ragnarok,--,--,3,11,--,--,1,120,30,30,99,4.8,16,--,"Myth units, Set Animal",,Hero
46,Peltast,3,60W 20G,2,--,3,--,16,70,15,20,99,4,20,9,Ranged Infantary,,Ranged Infantary
47,Gastraphetes,4,120W 80G,3,--,8,6,24,60,15,15,99,3.8,28,14,,,Ranged Infantary
48,Petrobolos,3,150W 200G,3,--,5,11,28,110,30,90,90,2.4,40,19,Ships,,Siege
49,Helepolis,4,300W 200G,5,--,5,17*,10,650,5,96,50,2.9,18,24,,Transports,Siege
50,Myrmidon,4,70F 50G,2,10,--,--,1,110,45,20,99,4,16,14,Norse/Greek,,Melee Infantary
51,Hetairoi,4,60F 100G,3,8,--,--,1,110,10,40,99,4.8,16,17,Buildings,,Cavalry
52,Spearman,2,50F 20G,2,7,--,--,2,70,40,20,99,5,16,9,"Cavalry, Siege",,Spear Infantary
53,Axeman,2,40F 30G,2,5,--,--,1,70,40,5,99,4.3,16,10,Infantry,,Melee Infantary
54,Slinger,2,60W 24G,2,--,3,--,16,65,15,20,99,4,20,14,Ranged Infantary,,Ranged Infantary
55,Chariot Archer,3,100W 40G,3,--,8.5,--,20,90,30,20,99,5,24,6,,,Ranged Cavalry
56,Camelry,3,50F 70G,3,8,--,--,1,125,15,30,99,6,16,9,Cavalry,,Cavalry
57,War Elephant,3,180F 70G,5,14,--,--,1,450,25,40,99,2.9,16,15,Buildings,,Cavalry
58,Mercenary,1,90G,0,8,--,--,1,85,45,30,99,4.3,20,1,,Lifespan,Melee Infantary
59,Mercenary Cavalry,3,120G,0,8,--,--,1,190,40,45,99,5.3,22,3,,Lifespan,Cavalry
60,Ulfsark,1,50F 30G,2,9,--,--,1,80,30,10,99,4.8,16,9,"Obelisks, Turmas",,Melee Infantary
61,Throwing Axeman,2,"50W, 40G",2,4.5,--,--,9,65,30,10,99,4,16,16,"Norse Heroes, Infantry",,Ranged Infantary
62,Raiding Cavalry,2,"40F, 50G",2,8,--,--,1,105,20,35,99,6,8,18,"Ranged Infantary, Siege",,Cavalry
63,Huskarl,3,"75W, 40G",2,8,--,--,1,115,15,50,99,5,16,9,"Ranged Infantary, Cheiroballista",,Melee Infantary
64,Jarl,3,"50F, 80G",3,9,--,--,1,180,20,35,99,4.8,16,9,"Myth Units, Set Animals",,Cavalry
65,Portable Ram,3,125W 125G,3,--,--,40*,1,215,5,99,90,3.25,14,17,,,Siege
66,Ballista,4,150W 150G,3,--,9,4,30,85,20,80,90,2.4,40,17,,,Siege
67,Siege Tower,3,200W 100G,3,--,3,50,12,300,5,96,90,2.9,20,19,,Transports,Siege
68,Catapult,4,200W 200G,3,--,10,50,28,115,30,90,80,2.4,40,24,Ships,,Siege
69,Ape of Set,1,4Fv,2,5,--,--,1,45,35%,20%,99%,3.2,16,20,-Buildings,,Animal
70,Gazelle of Set,2,4Fv,2,4,--,--,1,20,35%,0%,99%,5,16,20,-Buildings,,Animal
71,Hyena of Set,2,6Fv,2,8,--,--,0,45,20%,30%,99%,3.2,16,20,-Buildings,,Animal
72,Giraffe of Set,3,7Fv,2,6,--,--,1,30,35%,5%,99%,5,16,20,-Buildings,,Animal
73,Crocodile of Set,3,8Fv,2,14,--,--,1,90,10%,30%,99%,5.3,18,24,-Buildings,,Animal
74,Hippo of Set,4,12Fv,2,12,--,--,1,130,10%,20%,99%,4,18,17,-Buildings,,Animal
75,Rhino of Set,4,16Fv,3,12,--,--,1,180,30%,40%,99%,3.6,20,20,-Buildings,,Animal
76,Fishing boat,1,50W,1,--,--,--,1,120,60%,50%,5%,4.8,20,14,,,Ship
77,Transport,2,120W,2,--,--,--,0,180,40%,80%,5%,5.3,14,19,,Transports,Ship
78,Longboat,2,100W 50G,2,--,6,--,12,290,30%,20%,10%,6,24,14,,Transports,Ship
79,Drakkar,3,100W 50G,2,20,--,--,1,240,20%,20%,75%,7,16,12,,,Ship
80,Dragon Boat,3,100W 100G,3,--,--,6,18,480,10%,50%,10%,4.8,24,17,-Buildings,,Ship
81,Kraken,3,300F 25Fv,5,15,--,5,1,900,50%,70%,80%,6,22,10,,,Myth Unit
82,Jormund Elver,4,200F 15Fv,3,--,40,--,20,800,20%,30%,80%,6,24,5,,,Myth Unit

In [12]:

import pandas as pd

RECURSOS = {
    "F": "cost_food",
    "W": "cost_wood",
    "G": "cost_gold",
    "Fv": "cost_favor",
}

COLUNAS_NUMERICAS = [
    "age", "pop", "dmg_hack", "dmg_pierce", "dmg_crush",
    "range", "hp", "armor_hack", "armor_pierce",
    "armor_crush", "speed", "los", "train_time",
]


def extrair_custos(valor):
    if pd.isna(valor) or valor in ("", "--"):
        return {nome: 0 for nome in RECURSOS.values()}

    custos = {nome: 0 for nome in RECURSOS.values()}

    for item in valor.replace(",", " ").split():
        recurso = next(
            (r for r in RECURSOS if item.endswith(r)),
            None
        )

        if recurso is None:
            raise ValueError(f"Custo inválido: {item}")

        quantidade = item.removesuffix(recurso)

        if not quantidade.isdigit():
            raise ValueError(f"Custo inválido: {item}")

        custos[RECURSOS[recurso]] += int(quantidade)

    return custos


def limpar_dataset(df) -> pd.DataFrame:
    df = df.copy()

    # Padroniza espaços e valores ausentes
    df.columns = [
        " ".join(col.replace("\u00a0", " ").split())
        for col in df.columns
    ]

    for coluna in df.columns:
        df[coluna] = df[coluna].map(
            lambda x: " ".join(x.replace("\u00a0", " ").split())
            if isinstance(x, str) else x
        )
    
    df = df.replace("", pd.NA)

    # Renomeia colunas
    df = df.rename(columns={
        "Unit": "unit",
        "Age": "age",
        "Cost": "cost_raw",
        "Pop": "pop",
        "DmgHack": "dmg_hack",
        "DmgPierce": "dmg_pierce",
        "DmgCrush": "dmg_crush",
        "Range": "range",
        "HP": "hp",
        "ArmorHack": "armor_hack",
        "ArmorPierce": "armor_pierce",
        "ArmorCrush": "armor_crush",
        "Speed": "speed",
        "LOS": "los",
        "Train time": "train_time",
        "Bonus": "bonus",
        "Other": "other",
        "Class": "unit_class",
    })

    # Corrige erros de escrita
    for coluna in ["unit_class", "bonus"]:
        df[coluna] = df[coluna].str.replace(
            "Infantary", "Infantry", regex=False
        )

    # Extrai custos
    custos = df["cost_raw"].apply(extrair_custos)
    custos = pd.DataFrame(custos.tolist(), index=df.index)

    for coluna in custos.columns:
        df[coluna] = custos[coluna].astype("Int64")

    # Remove marcações dos danos
    for coluna in ["dmg_hack", "dmg_pierce", "dmg_crush"]:
        df[coluna] = df[coluna].str.replace("*", "", regex=False)

    # Corrige HP
    df["hp"] = df["hp"].str.removesuffix("_")

    # Remove símbolo de porcentagem das armaduras
    for coluna in ["armor_hack", "armor_pierce", "armor_crush"]:
        df[coluna] = df[coluna].str.removesuffix("%")

    colunas_dmg = ["dmg_hack", "dmg_pierce", "dmg_crush"]

    df["does_attack"] = df[colunas_dmg].ne("--").any(axis=1).astype(int)


    # Converte colunas numéricas
    for coluna in COLUNAS_NUMERICAS:

        substituicoes = {
            "--": 0 if coluna.startswith("dmg_") else pd.NA,
            "none": pd.NA,
        }

        df[coluna] = pd.to_numeric(
            df[coluna].replace(substituicoes),
            errors="raise"
        )

    # Define tipos
    colunas_inteiras = [
        "age", "pop", "range", "hp",
        "armor_hack", "armor_pierce", "armor_crush",
        "los", "train_time",
    ]

    colunas_decimais = [
        "dmg_hack", "dmg_pierce", "dmg_crush", "speed",
    ]

    df[colunas_inteiras] = df[colunas_inteiras].astype("Int64")
    df[colunas_decimais] = df[colunas_decimais].astype("Float64")

    # Remove duplicatas
    df = df.drop_duplicates().reset_index(drop=True)

    # Valida valores
    for coluna in ["armor_hack", "armor_pierce", "armor_crush"]:
        if (df[coluna].dropna() > 100).any():
            raise ValueError(f"Armadura inválida: {coluna}")

    # Organiza colunas
    ordem = [
        "unit", "unit_class", "age",
        "cost_food", "cost_wood", "cost_gold", "cost_favor",
        "pop", "hp",
        "dmg_hack", "dmg_pierce", "dmg_crush",
        "armor_hack", "armor_pierce", "armor_crush",
        "range", "speed", "los", "train_time",
        "bonus", "other",
    ]

    return df[ordem]

In [13]:
df_limpo = limpar_dataset(df)

In [14]:
display(df_limpo)

,unit,unit_class,age,cost_food,cost_wood,cost_gold,cost_favor,pop,hp,dmg_hack,dmg_pierce,dmg_crush,armor_hack,armor_pierce,armor_crush,range,speed,los,train_time,bonus,other
0,Pegasus,Myth Unit,1,50,0,0,2,2,140,0.0,0.0,0.0,50,50,99,0,5.0,18,6,NaN,NaN
1,Centaur,Myth Unit,2,0,200,0,15,3,220,0.0,12.0,0.0,25,35,80,12,5.0,20,19,"Myth units, -Heroes",NaN
2,Cyclops,Myth Unit,2,250,0,0,22,4,600,15.0,0.0,12.0,40,50,80,2,3.2,16,20,Myth units,NaN
3,Minotaur,Myth Unit,2,200,0,0,16,4,300,15.0,0.0,10.0,60,50,80,2,4.0,20,20,Myth units,NaN
4,Hydra,Myth Unit,3,250,0,0,28,5,800,20.0,0.0,10.0,60,40,80,3,4.0,16,20,"Myth units, -Heroes",NaN
5,Manticore,Myth Unit,3,0,300,0,28,5,420,0.0,11.0,0.0,30,60,80,16,4.3,20,17,"Myth units, -Heroes",NaN
6,Nemean Lion,Myth Unit,3,0,0,200,25,4,660,20.0,0.0,10.0,30,60,80,1,4.8,16,20,"Myth units, -Heroes",NaN
7,Colossus,Myth Unit,4,0,0,300,40,5,1100,20.0,0.0,50.0,50,80,80,3,2.4,16,24,"Myth units, -Heroes",NaN
8,Chimera,Myth Unit,4,0,0,300,30,4,800,20.0,0.0,0.0,60,60,80,1,5.3,16,20,"Myth units, -Heroes",NaN
9,Medusa,Myth Unit,4,0,0,250,40,5,360,0.0,15.0,12.5,60,70,80,10,4.3,18,20,"Myth units, -Heroes",NaN
10,Anubite,Myth Unit,2,100,0,0,15,3,200,13.0,0.0,0.0,60,55,80,1,5.3,16,9,Myth units,NaN
11,Sphinx,Myth Unit,2,60,0,0,10,4,300,11.25,0.0,5.0,45,60,80,1,5.3,22,17,Myth units,NaN
12,Wadjet,Myth Unit,2,0,150,0,15,3,240,0.0,16.0,0.0,20,30,80,18,3.8,20,17,-Heroes,NaN
13,Petsuchos,Myth Unit,3,0,0,200,20,4,480,0.0,50.0,20.0,30,40,80,20,2.6,24,20,-Heroes,NaN
14,Roc,Myth Unit,3,0,0,150,15,3,350,0.0,0.0,0.0,30,25,80,<NA>,4.8,20,14,NaN,Transports
15,Scarab,Myth Unit,3,300,0,0,20,5,670,6.0,0.0,12.0,30,75,80,1,3.2,16,20,Buildings,NaN
16,Scorpion Man,Myth Unit,3,0,150,0,25,4,500,25.0,0.0,0.0,50,40,80,1,5.0,16,20,"Myth units, -Heroes",NaN
17,Avenger,Myth Unit,4,250,0,0,30,4,600,28.0,0.0,0.0,60,40,80,1,5.3,18,24,"Myth units, -Heroes",NaN
18,Mummy,Myth Unit,4,0,0,200,35,5,350,0.0,12.0,0.0,35,50,80,12,4.0,18,17,NaN,NaN
19,Phoenix,Myth Unit,4,0,0,200,30,5,400,30.0,0.0,30.0,15,55,80,4,3.6,20,20,-Heroes,NaN
20,Einherjar,Myth Unit,2,0,0,175,15,3,275,15.0,0.0,10.0,70,60,80,1,3.2,16,17,Myth units,NaN
21,Troll,Myth Unit,2,0,150,0,15,4,200,0.0,13.0,0.0,50,50,80,14,3.6,20,15,"Myth units, -Heroes",NaN
22,Valkyrie,Myth Unit,2,200,0,0,20,4,375,12.0,0.0,0.0,55,70,80,1,6.0,20,17,Myth units,NaN
23,Battle Boar,Myth Unit,3,0,0,250,30,4,720,20.0,0.0,20.0,60,60,80,1,5.3,16,20,"Myth units, -Heroes",NaN
24,Frost Giant,Myth Unit,3,0,0,200,25,5,600,18.0,0.0,12.0,55,70,80,2,3.8,20,24,x3 Myth units,NaN
25,Mountain Giant,Myth Unit,3,300,0,0,30,5,1200,20.0,0.0,25.0,45,30,80,2,3.2,16,17,"x2 Myth units, x0.8 Heroes",NaN
26,Fenris Wolf,Myth Unit,4,0,0,150,15,3,420,15.0,0.0,0.0,40,50,80,1,4.0,16,14,"x2 Myth units, x0.5 Heroes",NaN
27,Fire Giant,Myth Unit,4,0,0,300,35,5,600,15.0,0.0,10.0,60,80,80,14,3.2,18,24,x0.25 Heroes,NaN
28,Jason,Hero,1,100,0,50,0,2,240,9.0,0.0,0.0,25,35,99,1,4.3,16,9,Myth units,NaN
29,Odysseus,Hero,2,0,200,0,2,2,320,0.0,8.0,0.0,20,30,99,18,4.0,20,17,Myth units,NaN
30,Heracles,Hero,3,350,0,0,4,3,400,10.0,0.0,0.0,25,40,99,1,4.3,16,23,Myth units,NaN
31,Bellerophon,Hero,4,0,0,400,6,4,400,20.0,0.0,0.0,20,40,99,2,6.0,16,27,Myth units,NaN
32,Theseus,Hero,1,100,0,50,0,2,240,9.0,0.0,0.0,25,40,99,1,4.3,16,9,Myth units,NaN
33,Hippolyta,Hero,2,0,200,0,2,2,240,0.0,9.0,0.0,20,30,99,18,4.3,20,17,Myth units,NaN
34,Atalanta,Hero,3,350,0,0,4,3,350,8.0,0.0,0.0,35,40,99,2,6.0,16,23,Myth units,NaN
35,Polyphemus,Hero,4,0,0,400,6,4,540,15.0,0.0,5.0,40,40,99,2,3.2,20,27,Myth units,NaN
36,The Argo,Hero,4,250,0,0,8,3,480,0.0,8.0,0.0,40,25,20,16,4.8,24,17,Myth units,Transports
37,Ajax,Hero,1,100,0,50,0,2,240,9.0,0.0,0.0,30,25,99,1,4.3,16,9,Myth units,NaN
38,Chiron,Hero,2,0,200,0,2,2,300,0.0,7.0,0.0,20,20,99,14,5.3,20,17,Myth units,NaN
39,Achilles,Hero,3,350,0,0,4,3,340,9.0,0.0,0.0,40,45,99,1,5.5,16,23,Myth units,NaN
40,Perseus,Hero,4,0,0,400,6,4,360,7.0,0.0,0.0,20,40,99,1,4.3,16,27,Myth units,NaN
41,Priest,Hero,1,0,0,100,0,2,90,0.0,3.0,0.0,10,0,99,3,3.6,8,9,Myth units,NaN
42,Pharaoh,Hero,1,0,0,0,0,0,100,0.0,12.0,0.0,15,15,99,4,4.0,16,<NA>,Myth units,NaN
43,Son of Osiris,Hero,<NA>,0,0,0,0,<NA>,546,60.0,0.0,0.0,30,50,99,18,3.6,25,<NA>,Myth units,Up to 4
44,Hersir,Hero,2,80,0,40,0,3,130,8.0,0.0,0.0,20,15,99,1,4.2,16,23,Myth units,Double Favor
45,Hero of Ragnarok,Hero,<NA>,0,0,0,0,3,120,11.0,0.0,0.0,30,30,99,1,4.8,16,<NA>,"Myth units, Set Animal",NaN
46,Peltast,Ranged Infantry,3,0,60,20,0,2,70,0.0,3.0,0.0,15,20,99,16,4.0,20,9,Ranged Infantry,NaN
47,Gastraphetes,Ranged Infantry,4,0,120,80,0,3,60,0.0,8.0,6.0,15,15,99,24,3.8,28,14,NaN,NaN
48,Petrobolos,Siege,3,0,150,200,0,3,110,0.0,5.0,11.0,30,90,90,28,2.4,40,19,Ships,NaN
49,Helepolis,Siege,4,0,300,200,0,5,650,0.0,5.0,17.0,5,96,50,10,2.9,18,24,NaN,Transports
50,Myrmidon,Melee Infantry,4,70,0,50,0,2,110,10.0,0.0,0.0,45,20,99,1,4.0,16,14,Norse/Greek,NaN
51,Hetairoi,Cavalry,4,60,0,100,0,3,110,8.0,0.0,0.0,10,40,99,1,4.8,16,17,Buildings,NaN
52,Spearman,Spear Infantry,2,50,0,20,0,2,70,7.0,0.0,0.0,40,20,99,2,5.0,16,9,"Cavalry, Siege",NaN
53,Axeman,Melee Infantry,2,40,0,30,0,2,70,5.0,0.0,0.0,40,5,99,1,4.3,16,10,Infantry,NaN
54,Slinger,Ranged Infantry,2,0,60,24,0,2,65,0.0,3.0,0.0,15,20,99,16,4.0,20,14,Ranged Infantry,NaN
55,Chariot Archer,Ranged Cavalry,3,0,100,40,0,3,90,0.0,8.5,0.0,30,20,99,20,5.0,24,6,NaN,NaN
56,Camelry,Cavalry,3,50,0,70,0,3,125,8.0,0.0,0.0,15,30,99,1,6.0,16,9,Cavalry,NaN
57,War Elephant,Cavalry,3,180,0,70,0,5,450,14.0,0.0,0.0,25,40,99,1,2.9,16,15,Buildings,NaN
58,Mercenary,Melee Infantry,1,0,0,90,0,0,85,8.0,0.0,0.0,45,30,99,1,4.3,20,1,NaN,Lifespan
59,Mercenary Cavalry,Cavalry,3,0,0,120,0,0,190,8.0,0.0,0.0,40,45,99,1,5.3,22,3,NaN,Lifespan
60,Ulfsark,Melee Infantry,1,50,0,30,0,2,80,9.0,0.0,0.0,30,10,99,1,4.8,16,9,"Obelisks, Turmas",NaN
61,Throwing Axeman,Ranged Infantry,2,0,50,40,0,2,65,4.5,0.0,0.0,30,10,99,9,4.0,16,16,"Norse Heroes, Infantry",NaN
62,Raiding Cavalry,Cavalry,2,40,0,50,0,2,105,8.0,0.0,0.0,20,35,99,1,6.0,8,18,"Ranged Infantry, Siege",NaN
63,Huskarl,Melee Infantry,3,0,75,40,0,2,115,8.0,0.0,0.0,15,50,99,1,5.0,16,9,"Ranged Infantry, Cheiroballista",NaN
64,Jarl,Cavalry,3,50,0,80,0,3,180,9.0,0.0,0.0,20,35,99,1,4.8,16,9,"Myth Units, Set Animals",NaN
65,Portable Ram,Siege,3,0,125,125,0,3,215,0.0,0.0,40.0,5,99,90,1,3.25,14,17,NaN,NaN
66,Ballista,Siege,4,0,150,150,0,3,85,0.0,9.0,4.0,20,80,90,30,2.4,40,17,NaN,NaN
67,Siege Tower,Siege,3,0,200,100,0,3,300,0.0,3.0,50.0,5,96,90,12,2.9,20,19,NaN,Transports
68,Catapult,Siege,4,0,200,200,0,3,115,0.0,10.0,50.0,30,90,80,28,2.4,40,24,Ships,NaN
69,Ape of Set,Animal,1,0,0,0,4,2,45,5.0,0.0,0.0,35,20,99,1,3.2,16,20,-Buildings,NaN
70,Gazelle of Set,Animal,2,0,0,0,4,2,20,4.0,0.0,0.0,35,0,99,1,5.0,16,20,-Buildings,NaN
71,Hyena of Set,Animal,2,0,0,0,6,2,45,8.0,0.0,0.0,20,30,99,0,3.2,16,20,-Buildings,NaN
72,Giraffe of Set,Animal,3,0,0,0,7,2,30,6.0,0.0,0.0,35,5,99,1,5.0,16,20,-Buildings,NaN
73,Crocodile of Set,Animal,3,0,0,0,8,2,90,14.0,0.0,0.0,10,30,99,1,5.3,18,24,-Buildings,NaN
74,Hippo of Set,Animal,4,0,0,0,12,2,130,12.0,0.0,0.0,10,20,99,1,4.0,18,17,-Buildings,NaN
75,Rhino of Set,Animal,4,0,0,0,16,3,180,12.0,0.0,0.0,30,40,99,1,3.6,20,20,-Buildings,NaN
76,Fishing boat,Ship,1,0,50,0,0,1,120,0.0,0.0,0.0,60,50,5,1,4.8,20,14,NaN,NaN
77,Transport,Ship,2,0,120,0,0,2,180,0.0,0.0,0.0,40,80,5,0,5.3,14,19,NaN,Transports
78,Longboat,Ship,2,0,100,50,0,2,290,0.0,6.0,0.0,30,20,10,12,6.0,24,14,NaN,Transports
79,Drakkar,Ship,3,0,100,50,0,2,240,20.0,0.0,0.0,20,20,75,1,7.0,16,12,NaN,NaN
80,Dragon Boat,Ship,3,0,100,100,0,3,480,0.0,0.0,6.0,10,50,10,18,4.8,24,17,-Buildings,NaN
81,Kraken,Myth Unit,3,300,0,0,25,5,900,15.0,0.0,5.0,50,70,80,1,6.0,22,10,NaN,NaN
82,Jormund Elver,Myth Unit,4,200,0,0,15,3,800,0.0,40.0,0.0,20,30,80,20,6.0,24,5,NaN,NaN

Descobrir quantos dados tem de cada classe e quais coluna tem valor ausente

In [15]:
print(df_limpo.isna().sum()[lambda s: s > 0])   #colunas com valores ausentes
df_limpo["unit_class"].value_counts()

age            2
pop            1
range          1
train_time     3
bonus         17
other         73
dtype: int64

unit_class
Myth Unit          30
Hero               18
Animal              7
Siege               6
Cavalry             6
Melee Infantry      5
Ship                5
Ranged Infantry     4
Spear Infantry      1
Ranged Cavalry      1
Name: count, dtype: int64

Carregar o conjunto sem classe e escolher atributos

In [18]:
caminho_noClass = "https://www-usr.inf.ufsm.br/~joaquim/UFSM/DM/ds/AgeOfMythology_noClass.csv"
teste = pd.read_csv(caminho, dtype="string", keep_default_na=False, encoding="utf-8-sig")

In [19]:
teste

,Unit,Age,Cost,Pop,DmgHack,DmgPierce,DmgCrush,Range,HP,ArmorHack,ArmorPierce,ArmorCrush,Speed,LOS,Train time,Bonus,Other,Class
0,Pegasus,1,50F 2Fv,2,--,--,--,0,140,50,50,99,5,18,6,,,Myth Unit
1,Centaur,2,200W 15Fv,3,--,12,--,12,220,25,35,80,5,20,19,"Myth units, -Heroes",,Myth Unit
2,Cyclops,2,250F 22Fv,4,15,--,12,2,600,40,50,80,3.2,16,20,Myth units,,Myth Unit
3,Minotaur,2,200F 16Fv,4,15,--,10,2,300,60,50,80,4,20,20,Myth units,,Myth Unit
4,Hydra,3,250F 28Fv,5,20,--,10,3,800,60,40,80,4,16,20,"Myth units, -Heroes",,Myth Unit
5,Manticore,3,300W 28Fv,5,--,11**,--,16,420,30,60,80,4.3,20,17,"Myth units, -Heroes",,Myth Unit
6,Nemean Lion,3,200G 25Fv,4,20,--,10,1,660,30,60,80,4.8,16,20,"Myth units, -Heroes",,Myth Unit
7,Colossus,4,300G 40Fv,5,20,--,50,3,1100_,50,80,80,2.4,16,24,"Myth units, -Heroes",,Myth Unit
8,Chimera,4,300G 30Fv,4,20,--,--,1,800,60,60,80,5.3,16,20,"Myth units, -Heroes",,Myth Unit
9,Medusa,4,250G 40Fv,5,--,15,12.5,10,360,60,70,80,4.3,18,20,"Myth units, -Heroes",,Myth Unit
10,Anubite,2,100F 15Fv,3,13,--,--,1,200,60,55,80,5.3,16,9,Myth units,,Myth Unit
11,Sphinx,2,60F 10Fv,4,11.25,--,5,1,300,45,60,80,5.3,22,17,Myth units,,Myth Unit
12,Wadjet,2,150W 15Fv,3,--,16,--,18,240,20,30,80,3.8,20,17,-Heroes,,Myth Unit
13,Petsuchos,3,200G 20Fv,4,--,50,20,20,480,30,40,80,2.6,24,20,-Heroes,,Myth Unit
14,Roc,3,150G 15Fv,3,--,--,--,none,350,30,25,80,4.8,20,14,,Transports,Myth Unit
15,Scarab,3,300F 20Fv,5,6,--,12,1,670,30,75,80,3.2,16,20,Buildings,,Myth Unit
16,Scorpion Man,3,150W 25Fv,4,25,--,--,1,500,50,40,80,5,16,20,"Myth units, -Heroes",,Myth Unit
17,Avenger,4,250F 30Fv,4,28,--,--,1,600,60%,40%,80%,5.3,18,24,"Myth units, -Heroes",,Myth Unit
18,Mummy,4,200G 35Fv,5,--,12,--,12,350,35,50,80,4,18,17,,,Myth Unit
19,Phoenix,4,200G 30Fv,5,30,--,30,4,400,15,55,80,3.6,20,20,-Heroes,,Myth Unit
20,Einherjar,2,175G 15Fv,3,15,--,10,1,275,70,60,80,3.2,16,17,Myth units,,Myth Unit
21,Troll,2,150W 15Fv,4,--,13,--,14,200,50,50,80,3.6,20,15,"Myth units, -Heroes",,Myth Unit
22,Valkyrie,2,200F 20Fv,4,12,--,--,1,375,55,70,80,6,20,17,Myth units,,Myth Unit
23,Battle Boar,3,250G 30Fv,4,20,--,20,1,720,60,60,80,5.3,16,20,"Myth units, -Heroes",,Myth Unit
24,Frost Giant,3,200G 25Fv,5,18,--,12,2,600,55,70,80,3.8,20,24,x3 Myth units,,Myth Unit
25,Mountain Giant,3,300F 30Fv,5,20,--,25,2,1200,45,30,80,3.2,16,17,"x2 Myth units, x0.8 Heroes",,Myth Unit
26,Fenris Wolf,4,150G 15Fv,3,15,--,--,1,420,40,50,80,4,16,14,"x2 Myth units, x0.5 Heroes",,Myth Unit
27,Fire Giant,4,300G 35Fv,5,15,--,10,14,600,60,80,80,3.2,18,24,x0.25 Heroes,,Myth Unit
28,Jason,1,100F 50G,2,9,--,--,1,240,25,35,99,4.3,16,9,Myth units,,Hero
29,Odysseus,2,200W 2Fv,2,--,8*,--,18,320,20,30,99,4,20,17,Myth units,,Hero
30,Heracles,3,350F 4Fv,3,10,--,--,1,400,25,40,99,4.3,16,23,Myth units,,Hero
31,Bellerophon,4,400G 6Fv,4,20,--,--,2,400,20,40,99,6,16,27,Myth units,,Hero
32,Theseus,1,100F 50G,2,9,--,--,1,240,25,40,99,4.3,16,9,Myth units,,Hero
33,Hippolyta,2,200W 2Fv,2,--,9,--,18,240,20,30,99,4.3,20,17,Myth units,,Hero
34,Atalanta,3,350F 4Fv,3,8,--,--,2,350,35,40,99,6,16,23,Myth units,,Hero
35,Polyphemus,4,400G 6Fv,4,15,--,5,2,540,40,40,99,3.2,20,27,Myth units,,Hero
36,The Argo,4,250F 8Fv,3,--,8,--,16,480,40,25,20,4.8,24,17,Myth units,Transports,Hero
37,Ajax,1,100F 50G,2,9,--,--,1,240,30,25,99,4.3,16,9,Myth units,,Hero
38,Chiron,2,200W 2Fv,2,--,7,--,14,300,20,20,99,5.3,20,17,Myth units,,Hero
39,Achilles,3,350F 4Fv,3,9,--,--,1,340,40,45,99,5.5,16,23,Myth units,,Hero
40,Perseus,4,400G 6Fv,4,7,--,--,1,360,20,40,99,4.3,16,27,Myth units,,Hero
41,Priest,1,100G,2,--,3,--,3,90,10,0,99,3.6,8,9,Myth units,,Hero
42,Pharaoh,1,--,0,--,12,--,4,100,15,15,99,4,16,--,Myth units,,Hero
43,Son of Osiris,--,--,--,60,--,--,18,546,30,50,99,3.6,25,--,Myth units,Up to 4,Hero
44,Hersir,2,80F 40G,3,8,--,--,1,130,20,15,99,4.2,16,23,Myth units,Double Favor,Hero
45,Hero of Ragnarok,--,--,3,11,--,--,1,120,30,30,99,4.8,16,--,"Myth units, Set Animal",,Hero
46,Peltast,3,60W 20G,2,--,3,--,16,70,15,20,99,4,20,9,Ranged Infantary,,Ranged Infantary
47,Gastraphetes,4,120W 80G,3,--,8,6,24,60,15,15,99,3.8,28,14,,,Ranged Infantary
48,Petrobolos,3,150W 200G,3,--,5,11,28,110,30,90,90,2.4,40,19,Ships,,Siege
49,Helepolis,4,300W 200G,5,--,5,17*,10,650,5,96,50,2.9,18,24,,Transports,Siege
50,Myrmidon,4,70F 50G,2,10,--,--,1,110,45,20,99,4,16,14,Norse/Greek,,Melee Infantary
51,Hetairoi,4,60F 100G,3,8,--,--,1,110,10,40,99,4.8,16,17,Buildings,,Cavalry
52,Spearman,2,50F 20G,2,7,--,--,2,70,40,20,99,5,16,9,"Cavalry, Siege",,Spear Infantary
53,Axeman,2,40F 30G,2,5,--,--,1,70,40,5,99,4.3,16,10,Infantry,,Melee Infantary
54,Slinger,2,60W 24G,2,--,3,--,16,65,15,20,99,4,20,14,Ranged Infantary,,Ranged Infantary
55,Chariot Archer,3,100W 40G,3,--,8.5,--,20,90,30,20,99,5,24,6,,,Ranged Cavalry
56,Camelry,3,50F 70G,3,8,--,--,1,125,15,30,99,6,16,9,Cavalry,,Cavalry
57,War Elephant,3,180F 70G,5,14,--,--,1,450,25,40,99,2.9,16,15,Buildings,,Cavalry
58,Mercenary,1,90G,0,8,--,--,1,85,45,30,99,4.3,20,1,,Lifespan,Melee Infantary
59,Mercenary Cavalry,3,120G,0,8,--,--,1,190,40,45,99,5.3,22,3,,Lifespan,Cavalry
60,Ulfsark,1,50F 30G,2,9,--,--,1,80,30,10,99,4.8,16,9,"Obelisks, Turmas",,Melee Infantary
61,Throwing Axeman,2,"50W, 40G",2,4.5,--,--,9,65,30,10,99,4,16,16,"Norse Heroes, Infantry",,Ranged Infantary
62,Raiding Cavalry,2,"40F, 50G",2,8,--,--,1,105,20,35,99,6,8,18,"Ranged Infantary, Siege",,Cavalry
63,Huskarl,3,"75W, 40G",2,8,--,--,1,115,15,50,99,5,16,9,"Ranged Infantary, Cheiroballista",,Melee Infantary
64,Jarl,3,"50F, 80G",3,9,--,--,1,180,20,35,99,4.8,16,9,"Myth Units, Set Animals",,Cavalry
65,Portable Ram,3,125W 125G,3,--,--,40*,1,215,5,99,90,3.25,14,17,,,Siege
66,Ballista,4,150W 150G,3,--,9,4,30,85,20,80,90,2.4,40,17,,,Siege
67,Siege Tower,3,200W 100G,3,--,3,50,12,300,5,96,90,2.9,20,19,,Transports,Siege
68,Catapult,4,200W 200G,3,--,10,50,28,115,30,90,80,2.4,40,24,Ships,,Siege
69,Ape of Set,1,4Fv,2,5,--,--,1,45,35%,20%,99%,3.2,16,20,-Buildings,,Animal
70,Gazelle of Set,2,4Fv,2,4,--,--,1,20,35%,0%,99%,5,16,20,-Buildings,,Animal
71,Hyena of Set,2,6Fv,2,8,--,--,0,45,20%,30%,99%,3.2,16,20,-Buildings,,Animal
72,Giraffe of Set,3,7Fv,2,6,--,--,1,30,35%,5%,99%,5,16,20,-Buildings,,Animal
73,Crocodile of Set,3,8Fv,2,14,--,--,1,90,10%,30%,99%,5.3,18,24,-Buildings,,Animal
74,Hippo of Set,4,12Fv,2,12,--,--,1,130,10%,20%,99%,4,18,17,-Buildings,,Animal
75,Rhino of Set,4,16Fv,3,12,--,--,1,180,30%,40%,99%,3.6,20,20,-Buildings,,Animal
76,Fishing boat,1,50W,1,--,--,--,1,120,60%,50%,5%,4.8,20,14,,,Ship
77,Transport,2,120W,2,--,--,--,0,180,40%,80%,5%,5.3,14,19,,Transports,Ship
78,Longboat,2,100W 50G,2,--,6,--,12,290,30%,20%,10%,6,24,14,,Transports,Ship
79,Drakkar,3,100W 50G,2,20,--,--,1,240,20%,20%,75%,7,16,12,,,Ship
80,Dragon Boat,3,100W 100G,3,--,--,6,18,480,10%,50%,10%,4.8,24,17,-Buildings,,Ship
81,Kraken,3,300F 25Fv,5,15,--,5,1,900,50%,70%,80%,6,22,10,,,Myth Unit
82,Jormund Elver,4,200F 15Fv,3,--,40,--,20,800,20%,30%,80%,6,24,5,,,Myth Unit

In [ ]:
# padronizar 
mapa = {
    "Age": "age", "Pop": "pop",
    "DmgHack": "dmg_hack", "DmgPierce": "dmg_pierce", "DmgCrush": "dmg_crush",
    "Range": "range", "HP": "hp",
    "ArmorHack": "armor_hack", "ArmorPierce": "armor_pierce", "ArmorCrush": "armor_crush",
    "Speed": "speed", "Train time": "train_time", "Favor": "cost_favor",
}
teste = teste.rename(columns=mapa)

FEATURES = list(mapa.values())
treino = df_limpo[["unit_class"] + FEATURES].copy()
treino.head()

,unit_class,age,pop,dmg_hack,dmg_pierce,dmg_crush,range,hp,armor_hack,armor_pierce,armor_crush,speed,train_time,cost_favor
0,Myth Unit,1,2,0.0,0.0,0.0,0,140,50,50,99,5.0,6,2
1,Myth Unit,2,3,0.0,12.0,0.0,12,220,25,35,80,5.0,19,15
2,Myth Unit,2,4,15.0,0.0,12.0,2,600,40,50,80,3.2,20,22
3,Myth Unit,2,4,15.0,0.0,10.0,2,300,60,50,80,4.0,20,16
4,Myth Unit,3,5,20.0,0.0,10.0,3,800,60,40,80,4.0,20,28

In [ ]:

print(df_limpo.loc[df_limpo[FEATURES].isna().any(axis=1), ["unit", "unit_class"] + FEATURES])

                unit unit_class   age   pop  dmg_hack  dmg_pierce  dmg_crush  \
14               Roc  Myth Unit     3     3       0.0         0.0        0.0
42           Pharaoh       Hero     1     0       0.0        12.0        0.0
43     Son of Osiris       Hero  <NA>  <NA>      60.0         0.0        0.0
45  Hero of Ragnarok       Hero  <NA>     3      11.0         0.0        0.0

    range   hp  armor_hack  armor_pierce  armor_crush  speed  train_time  \
14   <NA>  350          30            25           80    4.8          14
42      4  100          15            15           99    4.0        <NA>
43     18  546          30            50           99    3.6        <NA>
45      1  120          30            30           99    4.8        <NA>

    cost_favor
14          15
42           0
43           0
45           0

Ajustar o valores ausentes para treino

In [24]:
treino[FEATURES] = treino[FEATURES].fillna(0).astype(float)
teste = teste[FEATURES].astype(float)

X = treino[FEATURES]
y = treino["unit_class"]

KeyError: "None of [Index(['age', 'pop', 'dmg_hack', 'dmg_pierce', 'dmg_crush', 'range', 'hp',\n       'armor_hack', 'armor_pierce', 'armor_crush', 'speed', 'train_time',\n       'cost_favor'],\n      dtype='str')] are in the [columns]"

In [ ]:
treino.groupby("unit_class")[["hp", "armor_crush", "cost_favor", "range", "speed"]].mean().round(1)